///### Toda rota que não seja GET exige o token, menos a rota de login ou registro
@Url = https://projeto-back-end-loadingjr.onrender.com
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicGVybWlzc2lvbiI6MiwiaWF0IjoxNzE2NjcxMDM4LCJleHAiOjE3MTY2NzI4Mzh9.IkSR-sNkv6AXN_P36Cgy2ZJUz9Kx5jsGtOc6E8glYss
POST {{Url}}/Login
Content-Type: application/json

{
    "username": "admin",
    "password": "adminpass"
}

###

//Criar uma postagem
POST {{Url}}/CriarPostagem
Authorization: Bearer {{Token}}
Content-Type: application/json

    {
        "title": "Titulo do post",
        "description": "Descrição da postagem",
        "post_type": "1",
        "imagem": "Mande a imagem aqui"
    }


###
//Rota que retona posts
GET {{Url}}/postagens


###
//Rota para edição de posts
PUT {{Url}}/EditarPostagem/64fb9fbc-18c8-4c74-a95e-87188181b080
Authorization:Bearer {{Token}}
Content-Type: application/json

    {
        "title":"Titulo do post",
        "description":"Descrição da postagem",
        "post_type": "2",
        "imagem": "Mande a imagem aqui"
    }

###

//Rota para edição de usuários
PUT {{Url}}/UserUpdate/:username
Authorization:Bearer {{Token}}
Content-Type: application/json

    {
        "username":"Novo username",
        "permission":"Nova permissão",

    }

###
//Registar um usuário
POST {{Url}}/Registro
Content-Type: application/json

{
    "username": "test",
    "password": "0007",
    "checkPassword": "0007"
}
###

//Deletar um post
DELETE {{Url}}/DeletarPostagem/64fb9fbc-18c8-4c74-a95e-87188181b080
Authorization:Bearer {{Token}}

###
//Deletar um usuário
DELETE {{Url}}/DeleteUser/:username
Authorization:Bearer {{Token}}

###
//Rota para buscar um usuário
GET {{Url}}/User/:username
Authorization:Bearer {{Token}}


###
//Rota que lista todos os usuário
GET {{Url}}/ListUsers
Authorization:Bearer {{Token}}
